import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import { CartProvider } from "@/context/Cart.context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative w-100 overflow-x-hidden">
        <CartProvider>
        <header>
          <Navbar />
        </header>
        <main>
          {children}
        </main>
          <footer className="bg-slate-100 py-4 text-center fixed bottom-0 w-full">
            <p>Got questions? Take a look at our <a href="/faq">FAQ</a> or <a href="/contact">contact us</a></p>
          </footer>
        </CartProvider>
      </body>
    </html>
  );
}
